application: dominoes-etc
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /candyland
  static_files: candyland.html
  upload: candyland.html

- url: /dominoes
  static_files: dominoes.html

  upload: dominoes.html
- url: /(css|fonts|js|images)/(.*)
  static_files: \1/\2
  upload: (css|fonts|js|images)/(.*)

- url: /.*
  script: main.app
